# Generated by Django 3.1.3 on 2020-12-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BabyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('sex', models.CharField(choices=[('boy', 'Boy'), ('girl', 'Girl')], default='boy', max_length=4)),
            ],
        ),
    ]
